name: Build (Top_Fuel)

on: [workflow_dispatch]

env:
  STREAMLINK_DIST_DIR: ${{ github.workspace }}/dist

jobs:
  windows-installer:
    name: Windows installer
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 300
      - name: Fetch tags
        run: git fetch --depth=300 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          ./script/install-dependencies.sh
          python -m pip install pynsist
          sudo apt update
          sudo apt install -y nsis imagemagick inkscape
      - name: Installer file name
        id: installer
        run: echo ::set-output name=filename::streamlink-$(python setup.py --version | sed 's/+/_/')
      - name: Build
        run: ./script/makeinstaller.sh "${{ steps.installer.outputs.filename }}"
      - name: Upload artifact
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{ steps.installer.outputs.filename }}-topfuel-win32
          path: ${{ env.STREAMLINK_DIST_DIR }}/${{ steps.installer.outputs.filename }}.exe
